[greeter]
background=/usr/share/backgrounds/koppa-os-wallpaper.png
theme-name=KOPPA-Dark
icon-theme-name=Adwaita
font-name=Monospace 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=slight
xft-rgba=rgb
indicators=~host;~spacer;~clock;~spacer;~session;~power
clock-format=%H:%M:%S  |  %A %d %B %Y
position=50%,center 50%,center
hide-user-image=false
default-user-image=/usr/share/icons/koppa-os/koppa-os.png
user-background=false
