#!/bin/sh
# KOPPA-OS live-build auto/config
# Compatible with live-build on Ubuntu 22.04 (lb 1:20211005)

set -e

lb config noauto \
    --distribution       bookworm \
    --archive-areas      "main contrib non-free non-free-firmware" \
    \
    --mirror-bootstrap          "http://deb.debian.org/debian" \
    --mirror-chroot             "http://deb.debian.org/debian" \
    --mirror-binary             "http://deb.debian.org/debian" \
    --mirror-chroot-security    "http://security.debian.org/debian-security" \
    --mirror-binary-security    "http://security.debian.org/debian-security" \
    \
    --apt-options        "--yes -oAcquire::Check-Valid-Until=false" \
    --apt-recommends     false \
    \
    --binary-image       iso-hybrid \
    --bootappend-live    "boot=live components net.ifnames=0 hostname=koppa-os" \
    \
    --debian-installer   live \
    --debian-installer-gui true \
    --initsystem         systemd \
    \
    --iso-application    "KOPPA-OS" \
    --iso-preparer       "KOPPA-OS Project" \
    --iso-publisher      "KOPPA-OS" \
    --iso-volume         "KOPPA-OS 1.0" \
    \
    --architectures      amd64 \
    \
    --linux-packages     "linux-image linux-headers" \
    --linux-flavours     amd64 \
    \
    --memtest            none \
    --win32-loader       false \
    \
    --firmware-binary    true \
    --firmware-chroot    true \
    \
    "${@}"
