---
defaultGroups:
    - sudo
    - audio
    - video
    - cdrom
    - plugdev
    - netdev
autologinGroup: autologin
doAutologin: false
doReusePassword: true
passwordRequirements:
    nonempty: true
setRootPassword: true
forbiddenPasswordSameAsUsername: false
userShell: /bin/bash
